/* ============================================================================
   /eclipse — THE SIGNATURE JOURNEY
   ----------------------------------------------------------------------------
   The only signature journey promoted in V1 (brief §1, §12), and the proof that
   the WELL framework can become a fully designed journey rather than a theme.

   TONE — the hardest thing on this page. Eclipse must read as DEEPER than a
   typical wellness stay without making the Discover Saint Lucia WELL umbrella
   synonymous with burnout (brief §12). So:

     · The recognition section describes a state, never diagnoses a person.
       "Still functioning. No longer restored." — not "you are burned out."
     · Every claim about what Eclipse does is about SEQUENCE, not treatment
       efficacy. We are not making clinical claims.
     · The safety note is not optional furniture. Eclipse is explicitly not a
       substitute for emergency, inpatient or acute medical care, and that
       sentence travels with the fit checklist wherever it appears.

   Copy is verbatim or near-verbatim from the Editorial Founding Edition
   (saint-lucia-well/content/copy.js spreads 15–22). Eclipse keeps the printed
   midnight/copper palette; that shift is deliberate.
   ========================================================================== */
'use strict';

const { VILLAGES } = require('./villages.js');

/* Village lookup by key, so a signature experience can be tagged with the
   village it happens in and inherit that village's accent. Eclipse used to sit
   beside the six villages as a separate product; tagging makes it the proof
   that the village system works. Pulling from VILLAGES rather than retyping
   colours means a village rename or recolour can never desync this page. */
const V = Object.fromEntries(VILLAGES.map((v) => [v.key, v]));

module.exports = {
  key: 'eclipse',
  path: '/eclipse',
  layout: 'destination',
  surface: 'consumer',
  title: 'Eclipse — a curated recovery journey through Saint Lucia',
  description: 'Not another retreat. A return to rhythm. Eclipse is a sequenced recovery journey through Saint Lucia, designed by practitioners and health professionals.',
  ogTitle: 'Eclipse — a return to rhythm',

  jsonLd: {
    '@context': 'https://schema.org',
    '@type': 'TouristTrip',
    name: 'Eclipse',
    description: 'A curated recovery journey through Saint Lucia, designed by practitioners and health professionals and delivered through place, hospitality and experience.',
    touristType: 'Wellness travellers seeking structured recovery',
    provider: { '@type': 'Organization', name: 'Discover Saint Lucia WELL' }
  },

  sections: [
    {
      type: 'pageHeader',
      id: 'eclipse-hero',
      mark: true,
      eyebrow: 'Signature journey',
      headline: 'Eclipse',
      lead: 'A curated recovery journey through Saint Lucia — designed by practitioners and health professionals, brought to life through place, hospitality and experience.',
      meta: ['Not another retreat. A return to rhythm.', '13°54′N 60°58′W'],

      /* Eclipse was the only page on the site whose first screen was flat
         colour. Widths are generated by tools/build-eclipse-images.py; the bare
         `src` is never fetched once `widths` is present — heroPicture() builds
         every candidate from it as a base. */
      img: {
        src: '/assets/eclipse/eclipse-hero.jpg',
        widths: [960, 1440, 2000],
        w: 2944, h: 1261,
        alt: ''
      },
      video: { webm: '/assets/video/eclipse-hero-loop.webm',
               mp4:  '/assets/video/eclipse-hero-loop.mp4' }
    },

    /* ── RECOGNITION ────────────────────────────────────────────────────── */
    {
      type: 'split',
      id: 'recognition',
      skin: 'eclipse',
      headline: 'Still functioning. No longer restored.',
      body: [
        /* The page previously fell from "a curated recovery journey" straight
           into depletion in one step. This line is the hinge: it names the
           tonal change as deliberate before the reader has to absorb it. */
        'Most Saint Lucia WELL journeys begin with what you want more of. Eclipse begins with what has stopped restoring you.',
        'They are still showing up. Still meeting expectations. Still carrying what needs to be carried.',
        'But sleep no longer fully restores. Effort has replaced ease. The body, mind and emotions no longer seem to move together.',
        'Eclipse is designed for this quieter form of depletion — not only collapse, but the gradual loss of internal rhythm.'
      ],
      /* Dropped "You are not broken." — asserting it puts the idea of being
         broken in front of the reader in order to deny it, which is the one
         thing this page is otherwise careful never to do. The second sentence
         was always carrying the meaning. */
      closing: 'You may simply be out of rhythm.',
      /* A real Saint Lucia photograph pushed into the Eclipse colour world —
         desaturated, darkened and tinted toward the printed edition's midnight.
         The place is unaltered in form; only the grade moves. The brochure
         already treats Eclipse as a separate colour world, and this is that
         rule applied to photography rather than to page furniture. */
      img: {
        src: '/assets/eclipse/eclipse-recognition-640.jpg',
        w: 640, h: 800,
        alt: 'The Pitons and the sea at low light, drained of colour.'
      }
    },

    /* ── WHAT MAKES IT DIFFERENT ────────────────────────────────────────── */
    {
      type: 'comparison',
      id: 'different',
      eyebrow: 'What makes Eclipse different',
      headline: 'Experience is the intervention.',
      lead: 'The value of Eclipse is not any single treatment, workshop, excursion or property. It comes from how each element is selected, paced and connected.',
      colA: {
        head: 'A typical wellness stay',
        items: [
          'Choose from a menu of activities',
          'Attend experiences independently',
          'Optimize or escape',
          'Limited preparation',
          'Limited support after departure'
        ]
      },
      colB: {
        head: 'Eclipse',
        items: [
          'Experiences intentionally sequenced',
          'Pacing based on readiness',
          'Environment, physiology and emotional work connected',
          'Guided entry before arrival',
          'Integration after returning home'
        ]
      },
      closing: 'Rainforest before deeper reflection. Movement before emotional release. Restoration after intensity. Ocean and sound for integration.',
      /* The island-wide repositioning, stated structurally rather than by
         naming a property — the arrangement can change between editions and
         this sentence still holds. Consistent with the claim discipline applied
         across the rest of the site. */
      footnote: 'Each edition is based at a single anchor property, with the signature experiences taking place across the villages — so the journey moves through the island rather than staying in one resort.'
    },

    /* ── THE ARC ────────────────────────────────────────────────────────── */
    {
      type: 'journeyArc',
      id: 'arc',
      mark: true,
      headline: 'Rhythm returns in phases.',
      /* The rhythm thesis lands here rather than in the recognition section.
         Recognition is where a reader asks "is this me?" — an explanation
         interrupts that. Here it does real work: it is the reason the journey
         is phased at all. */
      lead: 'Rhythm governs how you sleep, how you feel, how you relate and how you move. When it is disrupted the body compensates and the mind accelerates. Depletion is rarely created in a single moment, and recovery should not be treated as one either — so Eclipse follows a gradual progression that respects readiness rather than turning wellbeing into another performance demand.',

      /* Decorative — the band carries no information the phases beneath do not,
         so it ships with an empty alt inside an aria-hidden wrapper. */
      img: {
        src: '/assets/eclipse/eclipse-arc.jpg',
        widths: [960, 1440, 2000],
        w: 2560, h: 1097,
        alt: ''
      },
      video: { mp4: '/assets/video/eclipse-arc-loop.mp4' },
      phases: [
        { k: 'ARRIVE',   s: 'Safety and softening' },
        { k: 'REGULATE', s: 'Sleep, nourishment and nervous-system support' },
        { k: 'REAWAKEN', s: 'Movement, sensory engagement and vitality' },
        { k: 'RELEASE',  s: 'Guided emotional and somatic work' },
        { k: 'RESTORE',  s: 'Treatments, rest and integration' },
        { k: 'RETURN',   s: 'Clarity, support and continuity' }
      ],
      footnote: 'Nothing is rushed. Nothing is forced. Each stage creates the conditions for the next.'
    },

    /* ── AN ILLUSTRATIVE JOURNEY ────────────────────────────────────────── */
    {
      type: 'dayPlan',
      id: 'five-days',
      headline: 'How the arc becomes days.',
      lead: 'One way the phases can be sequenced. Final pacing is set with you, not for you.',
      days: [
        { d: 'Day 1', t: 'Arrival and Softening',   items: ['Welcome supper', 'Cacao and arrival ritual', 'Guided stillness', 'Early sleep support'] },
        { d: 'Day 2', t: 'Reawakening',             items: ['Coastal walking meditation', 'Gentle movement', 'Breath and body awareness', 'Restorative free time'] },
        { d: 'Day 3', t: 'Earth and Nightfall',     items: ['Pitons, waterfalls or volcanic landscape', 'Nature immersion', 'Expressive movement', 'Nighttime sound and Yoga Nidra'] },
        { d: 'Day 4', t: 'Restoration and Heart',   items: ['Massage or recovery therapies', 'Supported wellbeing options', 'Breathwork and sound', 'Water or lantern ritual'] },
        { d: 'Day 5', t: 'Integration and Return',  items: ['Learning salon', 'Guided reflection', 'Float or sound integration', 'Closing dinner', 'Return-home commitments'] }
      ],
      footer: 'Illustrative only. Final sequencing, properties and experiences are subject to programme design and partner confirmation.'
    },

    /* ── SIGNATURE EXPERIENCES ──────────────────────────────────────────── */
    {
      type: 'tileGrid',
      id: 'experiences',
      eyebrow: 'Signature Eclipse experiences',
      headline: 'Nine experiences, across the whole island.',
      lead: 'Each one happens in the village that suits it — the rainforest for reflection, the water for release, the cacao estates for nourishment. Eclipse is the six villages sequenced into a single journey.',

      /* Descriptions come from the Executive Pack, trimmed to roughly a line
         each. Imagery is generated atmosphere — no named property, no
         identifiable face — which is what makes it publishable where the
         property library is not. Derivatives: tools/build-eclipse-images.py. */
      tiles: [
        { t: 'First Light', village: V.heritage,
          s: 'A five-course plant-based supper with cacao ceremony, and a guided arrival into stillness.',
          img: { base: '/assets/eclipse/eclipse-first-light', widths: [640, 960],
                 alt: 'A long candlelit table at dusk, set with plant-based courses and cacao bowls.' } },

        { t: 'The Rising Tide', village: V.movement,
          s: 'Beachside walking meditation flowing into soca-inspired somatic movement.',
          img: { base: '/assets/eclipse/eclipse-rising-tide', widths: [640, 960],
                 alt: 'Footprints along wet sand at the waterline, first light.' } },

        { t: 'Earth Descent', village: V.rainforest,
          s: 'A coastal journey through the Pitons, waterfalls and volcanic earth, ending in release.',
          img: { base: '/assets/eclipse/eclipse-earth-descent', widths: [640, 960],
                 alt: 'A waterfall falling into a pool deep in rainforest shade.' },
          video: { mp4: '/assets/video/earth-descent-loop.mp4' } },

        { t: 'The Phoenix Passage', village: V.rainforest,
          s: 'Guided breathwork and visualization, to process emotion and reach inner clarity.',
          img: { base: '/assets/eclipse/eclipse-phoenix-passage', widths: [640, 960],
                 alt: 'Light moving through mist — an abstract study.' } },

        { t: 'The Tides Within', village: V.ocean,
          s: 'Breathwork and sound to release what is held, closing with a lantern release over water.',
          img: { base: '/assets/eclipse/eclipse-tides-within', widths: [640, 960],
                 alt: 'Paper lanterns drifting across dark water at night, their reflections beneath.' },
          video: { mp4: '/assets/video/tides-within-loop.mp4' } },

        { t: 'Nightfall', village: V.longevity,
          s: 'A sleep-focused evening: nourishing dinner, sound bath, Yoga Nidra, nervous-system downshift.',
          img: { base: '/assets/eclipse/eclipse-nightfall', widths: [640, 960],
                 alt: 'A singing bowl and a candle on linen in a darkened room.' } },

        { t: 'The Learning Salon', village: V.connection,
          s: 'A guided energy audit and group session, bringing clarity to patterns and recovery.',
          img: { base: '/assets/eclipse/eclipse-learning-salon', widths: [640, 960],
                 alt: 'A circle of empty wooden chairs with notebooks, in daylight.' } },

        { t: 'Restorative Therapies', village: V.longevity,
          s: 'Optional advanced therapies supporting detox, recovery and nervous-system regulation.',
          img: { base: '/assets/eclipse/eclipse-restorative-therapies', widths: [640, 960],
                 alt: 'A treatment room in warm daylight, linen-covered table, no equipment on show.' } },

        { t: 'Ocean Within', village: V.ocean,
          s: 'An immersive sound and vocal journey at twilight, paired with float therapy.',
          img: { base: '/assets/eclipse/eclipse-ocean-within', widths: [640, 960],
                 alt: 'A single swimmer far below on open water, ripples spreading outward.' },
          video: { mp4: '/assets/video/ocean-within-loop.mp4' } }
      ],
      footnote: 'Experiences are sequenced to the arc and paced to you. Final selection is set during guided entry, before anything is booked.'
    },

    /* ── THE TEAM ───────────────────────────────────────────────────────── */
    {
      type: 'expertise',
      id: 'team',
      skin: 'eclipse',
      headline: 'Designed by specialists. Personalized by your advisor.',
      roles: [
        { role: 'Practitioners and health professionals', text: 'Design the recovery architecture, sequencing and facilitation.' },
        { role: 'Properties and hospitality teams',        text: 'Create the environments, service and comfort that allow the journey to unfold.' },
        { role: 'Local guides and cultural partners',      text: 'Bring Saint Lucia’s nature, food, stories and traditions to life.' },
        { role: 'Your travel advisor',                     text: 'Personalizes flights, rooms, companion travel, pre- and post-stays and everything around the journey itself.' }
      ],
      pullquote: 'The recovery journey is curated. The travel experience remains personal.'
    },

    /* ── FIT + SAFETY ───────────────────────────────────────────────────── */
    {
      type: 'checklist',
      id: 'fit',
      mark: true,
      eyebrow: 'Is this for you?',
      headline: 'Eclipse may be for you if…',
      /* The Executive Pack's three guest profiles, reworded ungendered — the
         pack frames Eclipse for women on p.10 and then devotes p.33 to men, so
         it contradicts itself; the site stays open. Named profiles are far more
         self-identifying than "you may be…" bullets, which is what a page whose
         next step is a conversation actually needs. The last three lines stay
         as conditions rather than characters, because readiness is not a type
         of person. */
      items: [
        'The overextended achiever — still performing at a high level, but recovery no longer holds. Sleep is inconsistent. Energy is managed rather than restored.',
        'At a threshold — sensing a shift personally, physically or relationally, where your current pace no longer matches who you are becoming.',
        'The private leader — carrying significant responsibility with little room for emotional release, and needing discretion, depth and precision.',
        'You want depth without a harsh or overly clinical environment.',
        'You value privacy, thoughtful guidance and exceptional hospitality.',
        'You are ready to participate in recovery, not simply observe it.'
      ],
      noteTitle: 'What Eclipse is not',
      note: 'Eclipse is not a substitute for emergency, inpatient or acute medical care, and it is not a clinical treatment programme. Guest suitability is considered through a guided entry process before booking.'
    },

    /* ── THE RETURN ─────────────────────────────────────────────────────── */
    {
      type: 'split',
      id: 'return',
      skin: 'eclipse',
      flip: true,
      headline: 'The journey does not end at departure.',
      /* Was "a pathway for integration afterwards" — vague where the Executive
         Pack is specific. Ninety days, a named form of support, and the honest
         framing that this is the point where change either holds or fades. */
      body: [
        'Guests return to the same responsibilities, relationships and environments. What changes is how they meet them. This is the point where change either holds or slowly fades.',
        'So Eclipse continues for ninety days after departure. Guidance carries on through your concierge, alongside an integration practitioner who helps insight become something you actually live rather than something you remember.'
      ],
      closing: 'Return with greater rhythm, clarity and capacity.',
      cta: { label: 'Speak with an advisor', href: '/about#contact' },
      ctaVariant: 'copper',
      /* Deliberately NOT graded. The page opens in the Eclipse world and closes
         in real light — the ungraded frame is the point, and grading it flattened
         the blue-to-gold horizon into mud. */
      img: {
        src: '/assets/dawn-horizon.jpg',
        w: 771, h: 998,
        /* `split` renders its media through figure(), which reads the loop from
           inside `img` — a sibling `video:` key here is silently ignored. */
        video: { webm: '/assets/video/return-dawn-loop.webm',
                 mp4:  '/assets/video/return-dawn-loop.mp4' },
        alt: 'First light over a calm sea, the island low on the horizon.',
        caption: 'The eclipse passing'
      }
    },

    {
      type: 'finalCta',
      id: 'begin',
      headline: 'Not sure Eclipse is the one?',
      lead: 'The Journey Finder starts from what you need, and shows you the parts of the island that answer it — Eclipse included, when it fits.',
      secondary: { label: 'Explore the villages', href: '/explore#villages' },
      /* The loop already exists and /explore already uses it — this CTA was
         showing the same still without the motion behind it. */
      video: { webm: '/assets/video/cta-dawn-loop.webm', mp4: '/assets/video/cta-dawn-loop.mp4' },
      img: {
        base: '/assets/cta/cta-dawn', widths: [771], w: 771, h: 330,
        src: '/assets/cta/cta-dawn-771.jpg', alt: ''
      }
    }
  ]
};
