#!/usr/bin/env node
/* ============================================================================
   media-test — the property imagery manifest, checked before any screen reads it
   ----------------------------------------------------------------------------
   content/properties-media.js is generated by tools/build-property-images.py
   and lifted into the knowledge bank by tools/build-well-knowledge.js. Two
   things can go quietly wrong between them: a frame can be described that is
   not on disk (a broken <img> on a call with a client watching), and the bank's
   copy-named-fields projection can drop the gallery so the Hub never sees it.
   This asserts both, plus the provenance every image must carry.

   Run: node tools/media-test.js
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const MEDIA = require(path.join(ROOT, 'content', 'properties-media.js'));
const K = require(path.join(ROOT, 'content', 'well-knowledge.generated.js'));

const KINDS = ['hero', 'spa', 'room', 'lobby', 'gym', 'activity', 'dining', 'exterior'];
const SOURCE_KINDS = ['property', 'press', 'ota'];
const MAX = 7;

let fails = 0;
const fail = (m) => { fails++; console.log('  FAIL  ' + m); };
const ok = (m) => console.log('  ok    ' + m);

console.log('\n  PROPERTY IMAGERY');
console.log('  ' + '-'.repeat(62));

/* ── 1. Every property record and every image in it ─────────────────────── */
const props = MEDIA.properties || {};
const folders = Object.keys(props);
let frames = 0, uncleared = 0, ota = 0;
const byKind = {};

folders.forEach((folder) => {
  const p = props[folder];
  const imgs = p.images || [];
  const where = folder;

  if (!imgs.length) fail(`${where}: no images[]`);
  if (imgs.length > MAX) fail(`${where}: ${imgs.length} images, more than ${MAX}`);
  const heroes = imgs.filter((i) => i.kind === 'hero');
  if (heroes.length !== 1) fail(`${where}: ${heroes.length} hero frames (want exactly one)`);
  if (imgs[0] && imgs[0].kind !== 'hero') fail(`${where}: images[0] is ${imgs[0].kind}, not the hero`);
  if (imgs[0] && imgs[0].base !== p.base) fail(`${where}: images[0].base differs from the flat hero base`);

  const bases = new Set();
  imgs.forEach((img, n) => {
    const tag = `${where} #${n} (${img.kind})`;
    frames++;
    byKind[img.kind] = (byKind[img.kind] || 0) + 1;
    if (KINDS.indexOf(img.kind) === -1) fail(`${tag}: kind not in the fixed list`);
    if (SOURCE_KINDS.indexOf(img.source_kind) === -1) fail(`${tag}: source_kind ${JSON.stringify(img.source_kind)}`);
    if (typeof img.cleared !== 'boolean') fail(`${tag}: cleared is not a boolean`);
    if (!img.cleared) uncleared++;
    if (img.source_kind === 'ota') ota++;
    if (!img.credit) fail(`${tag}: no credit`);
    if (typeof img.alt !== 'string' || img.alt.length < 20 || /\.(jpe?g|webp|png|avif)$/i.test(img.alt)) {
      fail(`${tag}: alt text reads like a filename or is too short: ${JSON.stringify(img.alt)}`);
    }
    /* Provenance. The two carried-forward properties are the only permitted
       gap, and they must say so on the record. */
    if (!img.source || !img.retrieved) {
      if (!p.provenanceNote) fail(`${tag}: no source/retrieved and no provenanceNote explaining why`);
    }
    if (bases.has(img.base)) fail(`${tag}: duplicate base ${img.base}`);
    bases.add(img.base);
    if (!Array.isArray(img.widths) || !img.widths.length) fail(`${tag}: no widths`);
    (img.widths || []).forEach((w) => {
      ['jpg', 'webp'].forEach((ext) => {
        const file = path.join(ROOT, img.base.replace(/^\//, '') + '-' + w + '.' + ext);
        if (!fs.existsSync(file)) fail(`${tag}: missing on disk ${path.relative(ROOT, file)}`);
      });
    });
    if (img.src !== `${img.base}-${img.widths[img.widths.length - 1]}.jpg`) fail(`${tag}: src is not the widest jpg`);
  });
});
if (!fails) ok(`${folders.length} properties, ${frames} frames, every width on disk in both formats`);

/* ── 2. The bank carries what the manifest carries ──────────────────────── */
const deep = (K.properties || []).filter((p) => p.collection === 'deep');
let bankFails = 0;
deep.forEach((p) => {
  const m = props[p.folder];
  if (!m) { fail(`bank ${p.slug}: folder ${p.folder} not in manifest`); bankFails++; return; }
  const got = (p.image && p.image.images) ? p.image.images.length : 0;
  if (got !== (m.images || []).length) { fail(`bank ${p.slug}: ${got} images in the bank, ${(m.images || []).length} in the manifest`); bankFails++; }
  ((p.image && p.image.images) || []).forEach((img, n) => {
    ['kind', 'base', 'widths', 'alt', 'source_kind', 'cleared', 'credit'].forEach((k) => {
      if (img[k] === undefined) { fail(`bank ${p.slug} #${n}: ${k} dropped by the projection`); bankFails++; }
    });
  });
});
if (!bankFails) ok(`bank: ${deep.length} deep properties carry the same image count as the manifest`);

/* ── 3. Nothing is cleared until Duncan says so ─────────────────────────── */
const cleared = frames - uncleared;
ok(`cleared ${cleared} · not yet cleared ${uncleared} · OTA-sourced ${ota}`);
ok('by kind: ' + KINDS.map((k) => `${k} ${byKind[k] || 0}`).join(' · '));

console.log(fails ? `\n  ${fails} FAILURE(S)\n` : '\n  PASS — every frame is on disk, tagged, credited and sourced; the bank sees all of them.\n');
process.exit(fails ? 1 : 0);
